export interface Country {
  name: string;
  code: string;
  iso2: string;
  flag: string;
  length: number;
}

export const COUNTRIES_LIST: Country[] = [
  { name: "Afghanistan", code: "+93", iso2: "AF", flag: "🇦🇫", length: 9 },
  { name: "Albania", code: "+355", iso2: "AL", flag: "🇦🇱", length: 9 },
  { name: "Algeria", code: "+213", iso2: "DZ", flag: "🇩🇿", length: 9 },
  { name: "Andorra", code: "+376", iso2: "AD", flag: "🇦🇩", length: 6 },
  { name: "Angola", code: "+244", iso2: "AO", flag: "🇦🇴", length: 9 },
  { name: "Antigua and Barbuda", code: "+1", iso2: "AG", flag: "🇦🇬", length: 7 },
  { name: "Argentina", code: "+54", iso2: "AR", flag: "🇦🇷", length: 10 },
  { name: "Armenia", code: "+374", iso2: "AM", flag: "🇦🇲", length: 8 },
  { name: "Australia", code: "+61", iso2: "AU", flag: "🇦🇺", length: 9 },
  { name: "Austria", code: "+43", iso2: "AT", flag: "🇦🇹", length: 10 },
  { name: "Azerbaijan", code: "+994", iso2: "AZ", flag: "🇦🇿", length: 9 },
  { name: "Bahamas", code: "+1", iso2: "BS", flag: "🇧🇸", length: 7 },
  { name: "Bahrain", code: "+973", iso2: "BH", flag: "🇧🇭", length: 8 },
  { name: "Bangladesh", code: "+880", iso2: "BD", flag: "🇧🇩", length: 10 },
  { name: "Barbados", code: "+1", iso2: "BB", flag: "🇧🇧", length: 7 },
  { name: "Belarus", code: "+375", iso2: "BY", flag: "🇧🇾", length: 9 },
  { name: "Belgium", code: "+32", iso2: "BE", flag: "🇧🇪", length: 9 },
  { name: "Belize", code: "+501", iso2: "BZ", flag: "🇧🇿", length: 7 },
  { name: "Benin", code: "+229", iso2: "BJ", flag: "🇧🇯", length: 8 },
  { name: "Bhutan", code: "+975", iso2: "BT", flag: "🇧🇹", length: 8 },
  { name: "Bolivia", code: "+591", iso2: "BO", flag: "🇧🇴", length: 8 },
  { name: "Bosnia and Herzegovina", code: "+387", iso2: "BA", flag: "🇧🇦", length: 8 },
  { name: "Botswana", code: "+267", iso2: "BW", flag: "🇧🇼", length: 8 },
  { name: "Brazil", code: "+55", iso2: "BR", flag: "🇧🇷", length: 11 },
  { name: "Brunei", code: "+673", iso2: "BN", flag: "🇧🇳", length: 7 },
  { name: "Bulgaria", code: "+359", iso2: "BG", flag: "🇧🇬", length: 9 },
  { name: "Burkina Faso", code: "+226", iso2: "BF", flag: "🇧🇫", length: 8 },
  { name: "Burundi", code: "+257", iso2: "BI", flag: "🇧🇮", length: 8 },
  { name: "Cambodia", code: "+855", iso2: "KH", flag: "🇰🇭", length: 9 },
  { name: "Cameroon", code: "+237", iso2: "CM", flag: "🇨🇲", length: 9 },
  { name: "Canada", code: "+1", iso2: "CA", flag: "🇨🇦", length: 10 },
  { name: "Cape Verde", code: "+238", iso2: "CV", flag: "🇨🇻", length: 7 },
  { name: "Central African Republic", code: "+236", iso2: "CF", flag: "🇨🇫", length: 8 },
  { name: "Chad", code: "+235", iso2: "TD", flag: "🇹🇩", length: 8 },
  { name: "Chile", code: "+56", iso2: "CL", flag: "🇨🇱", length: 9 },
  { name: "China", code: "+86", iso2: "CN", flag: "🇨🇳", length: 11 },
  { name: "Colombia", code: "+57", iso2: "CO", flag: "🇨🇴", length: 10 },
  { name: "Comoros", code: "+269", iso2: "KM", flag: "🇰🇲", length: 7 },
  { name: "Congo", code: "+242", iso2: "CG", flag: "🇨🇬", length: 9 },
  { name: "Costa Rica", code: "+506", iso2: "CR", flag: "🇨🇷", length: 8 },
  { name: "Croatia", code: "+385", iso2: "HR", flag: "🇭🇷", length: 9 },
  { name: "Cuba", code: "+53", iso2: "CU", flag: "🇨🇺", length: 8 },
  { name: "Cyprus", code: "+357", iso2: "CY", flag: "🇨🇾", length: 8 },
  { name: "Czech Republic", code: "+420", iso2: "CZ", flag: "🇨🇿", length: 9 },
  { name: "Denmark", code: "+45", iso2: "DK", flag: "🇩🇰", length: 8 },
  { name: "Djibouti", code: "+253", iso2: "DJ", flag: "🇩🇯", length: 8 },
  { name: "Dominica", code: "+1", iso2: "DM", flag: "🇩🇲", length: 7 },
  { name: "Dominican Republic", code: "+1", iso2: "DO", flag: "🇩🇴", length: 10 },
  { name: "Ecuador", code: "+593", iso2: "EC", flag: "🇪🇨", length: 9 },
  { name: "Egypt", code: "+20", iso2: "EG", flag: "🇪🇬", length: 10 },
  { name: "El Salvador", code: "+503", iso2: "SV", flag: "🇸🇻", length: 8 },
  { name: "Equatorial Guinea", code: "+240", iso2: "GQ", flag: "🇬🇶", length: 9 },
  { name: "Eritrea", code: "+291", iso2: "ER", flag: "🇪🇷", length: 7 },
  { name: "Estonia", code: "+372", iso2: "EE", flag: "🇪🇪", length: 8 },
  { name: "Eswatini", code: "+268", iso2: "SZ", flag: "🇸🇿", length: 8 },
  { name: "Ethiopia", code: "+251", iso2: "ET", flag: "🇪🇹", length: 9 },
  { name: "Fiji", code: "+679", iso2: "FJ", flag: "🇫🇯", length: 7 },
  { name: "Finland", code: "+358", iso2: "FI", flag: "🇫🇮", length: 9 },
  { name: "France", code: "+33", iso2: "FR", flag: "🇫🇷", length: 9 },
  { name: "Gabon", code: "+241", iso2: "GA", flag: "🇬🇦", length: 9 },
  { name: "Gambia", code: "+220", iso2: "GM", flag: "🇬🇲", length: 7 },
  { name: "Georgia", code: "+995", iso2: "GE", flag: "🇬🇪", length: 9 },
  { name: "Germany", code: "+49", iso2: "DE", flag: "🇩🇪", length: 10 },
  { name: "Ghana", code: "+233", iso2: "GH", flag: "🇬🇭", length: 9 },
  { name: "Greece", code: "+30", iso2: "GR", flag: "🇬🇷", length: 10 },
  { name: "Grenada", code: "+1", iso2: "GD", flag: "🇬🇩", length: 7 },
  { name: "Guatemala", code: "+502", iso2: "GT", flag: "🇬🇹", length: 8 },
  { name: "Guinea", code: "+224", iso2: "GN", flag: "🇬🇳", length: 9 },
  { name: "Guinea-Bissau", code: "+245", iso2: "GW", flag: "🇬🇼", length: 9 },
  { name: "Guyana", code: "+592", iso2: "GY", flag: "🇬🇾", length: 7 },
  { name: "Haiti", code: "+509", iso2: "HT", flag: "🇭🇹", length: 8 },
  { name: "Honduras", code: "+504, ", iso2: "HN", flag: "HN", length: 8 },
  { name: "Hong Kong", code: "+852", iso2: "HK", flag: "🇭🇰", length: 8 },
  { name: "Hungary", code: "+36", iso2: "HU", flag: "🇭🇺", length: 9 },
  { name: "Iceland", code: "+354", iso2: "IS", flag: "🇮🇸", length: 7 },
  { name: "India", code: "+91", iso2: "IN", flag: "🇮🇳", length: 10 },
  { name: "Indonesia", code: "+62", iso2: "ID", flag: "🇮🇩", length: 10 },
  { name: "Iran", code: "+98", iso2: "IR", flag: "🇮🇷", length: 10 },
  { name: "Iraq", code: "+964", iso2: "IQ", flag: "🇮🇶", length: 10 },
  { name: "Ireland", code: "+353", iso2: "IE", flag: "🇮🇪", length: 9 },
  { name: "Israel", code: "+972", iso2: "IL", flag: "🇮🇱", length: 9 },
  { name: "Italy", code: "+39", iso2: "IT", flag: "🇮🇹", length: 10 },
  { name: "Jamaica", code: "+1", iso2: "JM", flag: "🇯🇲", length: 7 },
  { name: "Japan", code: "+81", iso2: "JP", flag: "🇯🇵", length: 10 },
  { name: "Jordan", code: "+962", iso2: "JO", flag: "🇯🇴", length: 9 },
  { name: "Kazakhstan", code: "+7", iso2: "KZ", flag: "🇰🇿", length: 10 },
  { name: "Kenya", code: "+254", iso2: "KE", flag: "🇰🇪", length: 9 },
  { name: "Kiribati", code: "+686", iso2: "KI", flag: "🇰🇮", length: 8 },
  { name: "Kuwait", code: "+965", iso2: "KW", flag: "🇰🇼", length: 8 },
  { name: "Kyrgyzstan", code: "+996", iso2: "KG", flag: "🇰🇬", length: 9 },
  { name: "Laos", code: "+856", iso2: "LA", flag: "🇱🇦", length: 9 },
  { name: "Latvia", code: "+371", iso2: "LV", flag: "🇱🇻", length: 8 },
  { name: "Lebanon", code: "+961", iso2: "LB", flag: "🇱🇧", length: 8 },
  { name: "Lesotho", code: "+266", iso2: "LS", flag: "🇱🇸", length: 8 },
  { name: "Liberia", code: "+231", iso2: "LR", flag: "🇱🇷", length: 8 },
  { name: "Libya", code: "+218", iso2: "LY", flag: "🇱🇾", length: 9 },
  { name: "Liechtenstein", code: "+423", iso2: "LI", flag: "🇱🇮", length: 7 },
  { name: "Lithuania", code: "+370", iso2: "LT", flag: "🇱🇹", length: 8 },
  { name: "Luxembourg", code: "+352", iso2: "LU", flag: "🇱🇺", length: 9 },
  { name: "Macao", code: "+853", iso2: "MO", flag: "🇲🇴", length: 8 },
  { name: "Madagascar", code: "+261", iso2: "MG", flag: "🇲🇬", length: 9 },
  { name: "Malawi", code: "+265", iso2: "MW", flag: "🇲🇼", length: 9 },
  { name: "Malaysia", code: "+60", iso2: "MY", flag: "🇲🇾", length: 9 },
  { name: "Maldives", code: "+960", iso2: "MV", flag: "🇲🇻", length: 7 },
  { name: "Mali", code: "+223", iso2: "ML", flag: "🇲🇱", length: 8 },
  { name: "Malta", code: "+356", iso2: "MT", flag: "🇲🇹", length: 8 },
  { name: "Marshall Islands", code: "+692", iso2: "MH", flag: "🇲🇭", length: 7 },
  { name: "Mauritania", code: "+222", iso2: "MR", flag: "🇲🇷", length: 8 },
  { name: "Mauritius", code: "+230", iso2: "MU", flag: "🇲🇺", length: 8 },
  { name: "Mexico", code: "+52", iso2: "MX", flag: "🇲🇽", length: 10 },
  { name: "Micronesia", code: "+691", iso2: "FM", flag: "🇫🇲", length: 7 },
  { name: "Moldova", code: "+373", iso2: "MD", flag: "🇲🇩", length: 8 },
  { name: "Monaco", code: "+377", iso2: "MC", flag: "🇲🇨", length: 8 },
  { name: "Mongolia", code: "+976", iso2: "MN", flag: "🇲🇳", length: 8 },
  { name: "Montenegro", code: "+382", iso2: "ME", flag: "🇲🇪", length: 8 },
  { name: "Morocco", code: "+212", iso2: "MA", flag: "🇲🇦", length: 9 },
  { name: "Mozambique", code: "+258", iso2: "MZ", flag: "🇲🇿", length: 9 },
  { name: "Myanmar", code: "+95", iso2: "MM", flag: "🇲🇲", length: 9 },
  { name: "Namibia", code: "+264", iso2: "NA", flag: "🇳🇦", length: 8 },
  { name: "Nauru", code: "+674", iso2: "NR", flag: "🇳🇷", length: 7 },
  { name: "Nepal", code: "+977", iso2: "NP", flag: "🇳🇵", length: 10 },
  { name: "Netherlands", code: "+31", iso2: "NL", flag: "🇳🇱", length: 9 },
  { name: "New Zealand", code: "+64", iso2: "NZ", flag: "🇳🇿", length: 9 },
  { name: "Nicaragua", code: "+505", iso2: "NI", flag: "🇳🇮", length: 8 },
  { name: "Niger", code: "+227", iso2: "NE", flag: "🇳🇪", length: 8 },
  { name: "Nigeria", code: "+234", iso2: "NG", flag: "🇳🇬", length: 10 },
  { name: "North Korea", code: "+850", iso2: "KP", flag: "🇰🇵", length: 10 },
  { name: "North Macedonia", code: "+389", iso2: "MK", flag: "🇲🇰", length: 8 },
  { name: "Norway", code: "+47", iso2: "NO", flag: "🇳🇴", length: 8 },
  { name: "Oman", code: "+968", iso2: "OM", flag: "🇴🇲", length: 8 },
  { name: "Pakistan", code: "+92", iso2: "PK", flag: "🇵🇰", length: 10 },
  { name: "Palau", code: "+680", iso2: "PW", flag: "🇵🇼", length: 7 },
  { name: "Palestine", code: "+970", iso2: "PS", flag: "🇵🇸", length: 9 },
  { name: "Panama", code: "+507", iso2: "PA", flag: "🇵🇦", length: 8 },
  { name: "Papua New Guinea", code: "+675", iso2: "PG", flag: "🇵🇬", length: 8 },
  { name: "Paraguay", code: "+595", iso2: "PY", flag: "🇵🇾", length: 9 },
  { name: "Peru", code: "+51", iso2: "PE", flag: "🇵🇪", length: 9 },
  { name: "Philippines", code: "+63", iso2: "PH", flag: "🇵🇭", length: 10 },
  { name: "Poland", code: "+48", iso2: "PL", flag: "🇵🇱", length: 9 },
  { name: "Portugal", code: "+351", iso2: "PT", flag: "🇵🇹", length: 9 },
  { name: "Qatar", code: "+974", iso2: "QA", flag: "🇶🇦", length: 8 },
  { name: "Romania", code: "+40", iso2: "RO", flag: "🇷🇴", length: 9 },
  { name: "Russia", code: "+7", iso2: "RU", flag: "🇷🇺", length: 10 },
  { name: "Rwanda", code: "+250", iso2: "RW", flag: "🇷🇼", length: 9 },
  { name: "Saint Kitts and Nevis", code: "+1", iso2: "KN", flag: "🇰🇳", length: 7 },
  { name: "Saint Lucia", code: "+1", iso2: "LC", flag: "🇱🇨", length: 7 },
  { name: "Saint Vincent and the Grenadines", code: "+1", iso2: "VC", flag: "🇻🇨", length: 7 },
  { name: "Samoa", code: "+685", iso2: "WS", flag: "🇼🇸", length: 7 },
  { name: "San Marino", code: "+378", iso2: "SM", flag: "🇸🇲", length: 8 },
  { name: "Sao Tome and Principe", code: "+239", iso2: "ST", flag: "🇸🇹", length: 7 },
  { name: "Saudi Arabia", code: "+966", iso2: "SA", flag: "🇸🇦", length: 9 },
  { name: "Senegal", code: "+221", iso2: "SN", flag: "🇸🇳", length: 9 },
  { name: "Serbia", code: "+381", iso2: "RS", flag: "🇷🇸", length: 9 },
  { name: "Seychelles", code: "+248", iso2: "SC", flag: "🇸🇨", length: 7 },
  { name: "Sierra Leone", code: "+232", iso2: "SL", flag: "🇸🇱", length: 8 },
  { name: "Singapore", code: "+65", iso2: "SG", flag: "🇸🇬", length: 8 },
  { name: "Slovakia", code: "+421", iso2: "SK", flag: "🇸🇰", length: 9 },
  { name: "Slovenia", code: "+386", iso2: "SI", flag: "🇸🇮", length: 8 },
  { name: "Solomon Islands", code: "+677", iso2: "SB", flag: "🇸🇧", length: 7 },
  { name: "Somalia", code: "+252", iso2: "SO", flag: "🇸🇴", length: 9 },
  { name: "South Africa", code: "+27", iso2: "ZA", flag: "🇿🇦", length: 9 },
  { name: "South Korea", code: "+82", iso2: "KR", flag: "🇰🇷", length: 10 },
  { name: "South Sudan", code: "+211", iso2: "SS", flag: "🇸🇸", length: 9 },
  { name: "Spain", code: "+34", iso2: "ES", flag: "🇪🇸", length: 9 },
  { name: "Sri Lanka", code: "+94", iso2: "LK", flag: "🇱🇰", length: 9 },
  { name: "Sudan", code: "+249", iso2: "SD", flag: "🇸🇩", length: 9 },
  { name: "Suriname", code: "+597", iso2: "SR", flag: "🇸🇷", length: 7 },
  { name: "Sweden", code: "+46", iso2: "SE", flag: "🇸🇪", length: 9 },
  { name: "Switzerland", code: "+41", iso2: "CH", flag: "🇨🇭", length: 9 },
  { name: "Syria", code: "+963", iso2: "SY", flag: "🇸🇾", length: 9 },
  { name: "Taiwan", code: "+886", iso2: "TW", flag: "🇹🇼", length: 9 },
  { name: "Tajikistan", code: "+992", iso2: "TJ", flag: "🇹🇯", length: 9 },
  { name: "Tanzania", code: "+255", iso2: "TZ", flag: "🇹🇿", length: 9 },
  { name: "Thailand", code: "+66", iso2: "TH", flag: "🇹🇭", length: 9 },
  { name: "Timor-Leste", code: "+670", iso2: "TL", flag: "🇹🇱", length: 7 },
  { name: "Togo", code: "+228", iso2: "TG", flag: "🇹🇬", length: 8 },
  { name: "Tonga", code: "+676", iso2: "TO", flag: "🇹🇴", length: 7 },
  { name: "Trinidad and Tobago", code: "+1", iso2: "TT", flag: "🇹🇹", length: 7 },
  { name: "Tunisia", code: "+216", iso2: "TN", flag: "🇹🇳", length: 8 },
  { name: "Turkey", code: "+90", iso2: "TR", flag: "🇹🇷", length: 10 },
  { name: "Turkmenistan", code: "+993", iso2: "TM", flag: "🇹🇲", length: 8 },
  { name: "Tuvalu", code: "+688", iso2: "TV", flag: "🇹🇻", length: 7 },
  { name: "Uganda", code: "+256", iso2: "UG", flag: "🇺🇬", length: 9 },
  { name: "Ukraine", code: "+380", iso2: "UA", flag: "🇺🇦", length: 9 },
  { name: "United Arab Emirates", code: "+971", iso2: "AE", flag: "🇦🇪", length: 9 },
  { name: "United Kingdom", code: "+44", iso2: "GB", flag: "🇬🇧", length: 10 },
  { name: "United States", code: "+1", iso2: "US", flag: "🇺🇸", length: 10 },
  { name: "Uruguay", code: "+598", iso2: "UY", flag: "🇺🇾", length: 8 },
  { name: "Uzbekistan", code: "+998", iso2: "UZ", flag: "🇺🇿", length: 9 },
  { name: "Vanuatu", code: "+678", iso2: "VU", flag: "🇻🇺", length: 7 },
  { name: "Vatican City", code: "+39", iso2: "VA", flag: "🇻🇦", length: 10 },
  { name: "Venezuela", code: "+58", iso2: "VE", flag: "🇻🇪", length: 10 },
  { name: "Vietnam", code: "+84", iso2: "VN", flag: "🇻🇳", length: 9 },
  { name: "Yemen", code: "+967", iso2: "YE", flag: "🇾🇪", length: 9 },
  { name: "Zambia", code: "+260", iso2: "ZM", flag: "🇿🇲", length: 9 },
  { name: "Zimbabwe", code: "+263", iso2: "ZW", flag: "🇿🇼", length: 9 }
];
